### ISSUE TITLE
bug: the page status was not changed after the vote

### ISSUE THREAD

**Issue by zhanyeye** [nju-softeng/dingtalk-app-web#29]
#### 缺陷描述：
进入投票页面后，第一次投票，页面没有变化；第二次投票出现异常，但前端异常信息为null, (这里其实是后端 `Duplicate entry 'v_id-u_id' for key`, 重复投票的异常)

#### 问题分析：
投票后确实发送到后端了，但是前端没有正确切换到投票状态页面，后端异常信息也没提示 ”用户已投票“

+ 前端异常log：
```
POST http://47.104.103.33:8089/api/vote/52 500 ()
{timestamp: "2021-12-03", status: 500, error: "Internal Server Error", message: "", path: "/api/vote/52"}
```

+ 后端异常log:
```
Duplicate entry '52-27' for key 'vote_detail.UK61vpx1woxr2v6exm8a2hxwtgb'
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [vote_detail.UK61vpx1woxr2v6exm8a2hxwtgb]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '52-27' for key 'vote_detail.UK61vpx1woxr2v6exm8a2hxwtgb'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
........
```

**Comment by zhanyeye** [comment]
@lilingj 
+ hasVoted 忘记考虑投票后更新的情况
https://github.com/nju-softeng/dingtalk-app-web/blob/66333ce228d32e6bd8cdc0421bb0a8923a3fc7b2/src/views/paper/components/vote.vue#L184-L186

+ 原先投票之后，会取这里的值更新页面状态
https://github.com/nju-softeng/dingtalk-app-web/blob/66333ce228d32e6bd8cdc0421bb0a8923a3fc7b2/src/views/paper/components/vote.vue#L243-L247
